# General
session_name: tabulator-py

# Windows
windows:
  - window_name: bash
    panes:
      - shell_command:
        - source venv/bin/activate

  - window_name: vim
    panes:
      - shell_command:
        - source venv/bin/activate
        - vim
